pipeline {
    agent any
    
    environment {
        COLLECTION_FILE = 'collections/PetStoreAPI.postman_collection.json'
        ENVIRONMENT_FILE = 'environments/qa.postman_environment.json'
        REPORT_DIR = 'newman-reports'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Run Newman Tests') {
            steps {
                sh '''
                    mkdir -p ${REPORT_DIR}
                    newman run ${COLLECTION_FILE} \
                        -e ${ENVIRONMENT_FILE} \
                        -r cli,html,json,junit \
                        --reporter-junit-export ${REPORT_DIR}/results.xml \
                        --reporter-json-export ${REPORT_DIR}/results.json \
                        --reporter-html-export ${REPORT_DIR}/html/report.html
                '''
            }
        }
        
        stage('Publish Reports') {
            steps {
                junit allowEmptyResults: true, testResults: '${REPORT_DIR}/results.xml'
                publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: '${REPORT_DIR}',
                    reportFiles: 'html/report.html',
                    reportName: 'Newman HTML Report'
                ])
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Pipeline failed! Check reports for details.'
        }
    }
}
